# Default initial positions for Kinova's ros2_control fake system

initial_positions:
  j2n6s300_joint_1: 0.0
  j2n6s300_joint_2: 2.0
  j2n6s300_joint_3: 1.57
  j2n6s300_joint_4: 0
  j2n6s300_joint_5: 2.0
  j2n6s300_joint_6: 0.0
  j2n6s300_joint_finger_1: 0.0
  j2n6s300_joint_finger_2: 0.0
  j2n6s300_joint_finger_3: 0.0
  j2n6s300_joint_finger_tip_1: 0.0
  j2n6s300_joint_finger_tip_2: 0.0
  j2n6s300_joint_finger_tip_3: 0.0