# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: GripperCommand
    joints:
      - j2n6s300_joint_finger_1
      #- j2n6s300_joint_finger_tip_1
      - j2n6s300_joint_finger_2
      #- j2n6s300_joint_finger_tip_2
      - j2n6s300_joint_finger_3
      #- j2n6s300_joint_finger_tip_3
    action_ns: gripper_cmd
    default: true
