bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: "base_link"
    odom_topic: /odom
    transform_tolerance: 0.1
    default_nav_to_pose_bt_xml: "/home/yousef/ros2_workspaces/noham_ws/src/noham_path_planner/config/behavior.xml" # or $(find-pkg-share my_package)/behavior_tree/my_nav_to_pose_bt.xml
    always_reload_bt_xml: false
    goal_blackboard_id: goal
    goals_blackboard_id: goals
    path_blackboard_id: path
    navigators: ['navigate_to_pose']
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator" # In Iron and older versions, "/" was used instead of "::" # In Iron and older versions, "/" was used instead of "::"
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
      # - smoother_error_code, navigate_to_pose_error_code, navigate_through_poses_error_code, etc